/**:
  ros__parameters:
    num_robots: 3
    robot1_goal:
    - 1.25
    - 1.75
    robot1_initial_pose:
    - 0.0
    - 0.0
    - 0.0
    robot2_goal:
    - 1.25
    - 1.75
    robot2_initial_pose:
    - 0.0
    - 0.0
    - 0.0
    robot3_goal:
    - 1.25
    - 1.75
    robot3_initial_pose:
    - 0.0
    - 0.0
    - 0.0

