# Site settings
title: Fleet Robotics

# Theme settings
theme: jekyll-theme-minimal

# YAML Front Matter settings
yaml_front_matter: true


nav:
  - name: Home
    link: fleet_robotics/
  - name: System
    link: fleet_robotics/system
  - name: Progress
    link: fleet_robotics/progress
  - name: Galley
    link: fleet_robotics/gallery
  - name: Team
    link: fleet_robotics/team
# Other settings (optional)
#permalink: pretty
#paginate: 5