# Site settings
title: Fleet Robotics

# Theme settings
theme: jekyll-theme-minimal

# YAML Front Matter settings
yaml_front_matter: true


nav:
  - name: Home
    link: fleet_robotics
  - name: System
    link: system
  - name: Progress
    link: progress
  - name: Galley
    link: gallery
  - name: Team
    link: team
# Other settings (optional)
#permalink: pretty
#paginate: 5