# Site settings
title: Fleet Robotics

# Theme settings
theme: jekyll-theme-minimal

# YAML Front Matter settings
yaml_front_matter: true


nav:
  - name: Home
    link: /fleet_robotics
  - name: System
    link: system
    subitems:
      - name: Launch and Network
        link: launch
      - name: Path Planning
        link: path_planning
      - name: State Estimation
        link: state_estimation
  - name: Progress
    link: progress
    subitems:
      - name: -- Milestone 1
        link: m1
      - name: -- Milestone 2
        link: m2     
      - name: -- Final
        link: final     
  - name: Gallery
    link: gallery
  - name: Team
    link: team
  - name: Ethics
    link: ethics
  - name: GitHub
    link: https://github.com/itannermahncke/fleet_robotics

